[build-system]
requires = ["setuptools>=68", "wheel"]    
build-backend = "setuptools.build_meta"

[project]
name = "lsm"
version = "0.1.0"

[project.optional-dependencies]
test = ["pytest>=8"]

[tool.uv]
dev-dependencies = ["pytest"]
